## Early Stopping To Prevent Overfitting (For Epochs)

In [2]:
import pandas as pd
import io
import requests
import numpy as np

from sklearn import metrics
from sklearn.model_selection import train_test_split

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/iris.csv", 
    na_values=['NA', '?'])

# Convert to numpy - Classification
x = df[['sepal_l', 'sepal_w', 'petal_l', 'petal_w']].values

#First 20 Example (Row)
print(x[0:20])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]


In [3]:
df.head(5)

sepal_l  sepal_w  petal_l  petal_w      species
0      5.1      3.5      1.4      0.2  Iris-setosa
1      4.9      3.0      1.4      0.2  Iris-setosa
2      4.7      3.2      1.3      0.2  Iris-setosa
3      4.6      3.1      1.5      0.2  Iris-setosa
4      5.0      3.6      1.4      0.2  Iris-setosa

In [4]:
dummies = pd.get_dummies(df['species']) # Classification
dummies




Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

In [7]:
species = dummies.columns
print("species : ",species)
y = dummies.values
y[0:10]


species :  Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object')


array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]], dtype=uint8)

In [8]:
# Split into validation and training sets
x_train, x_test, y_train, y_test = train_test_split(    
    x, y, test_size=0.25, random_state=42)

print("x_train :",x_train[0:10])
print("y_train :",y_train[0:10])

x_train : [[5.  3.6 1.4 0.2]
 [5.2 4.1 1.5 0.1]
 [5.8 2.7 5.1 1.9]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [5.4 3.9 1.3 0.4]
 [5.4 3.7 1.5 0.2]
 [5.5 2.4 3.7 1. ]
 [6.3 2.8 5.1 1.5]
 [6.4 3.1 5.5 1.8]]
y_train : [[1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]


In [24]:
# Build neural network
model = Sequential()
model.add(Dense(50, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(25, activation='relu')) # Hidden 2
model.add(Dense(y.shape[1],activation='softmax')) # Output
model.compile(loss='categorical_crossentropy', optimizer='adam')

monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, 
        verbose=1, mode='auto', restore_best_weights=True)
model.fit(x_train,y_train,validation_data=(x_test,y_test),
        callbacks=[monitor],verbose=2,epochs=1000)

Epoch 1/1000
4/4 - 0s - loss: 1.2530 - val_loss: 1.1050
Epoch 2/1000
4/4 - 0s - loss: 1.0546 - val_loss: 1.0035
Epoch 3/1000
4/4 - 0s - loss: 0.9979 - val_loss: 0.9556
Epoch 4/1000
4/4 - 0s - loss: 0.9612 - val_loss: 0.8963
Epoch 5/1000
4/4 - 0s - loss: 0.9072 - val_loss: 0.8436
Epoch 6/1000
4/4 - 0s - loss: 0.8587 - val_loss: 0.8020
Epoch 7/1000
4/4 - 0s - loss: 0.8212 - val_loss: 0.7660
Epoch 8/1000
4/4 - 0s - loss: 0.7837 - val_loss: 0.7293
Epoch 9/1000
4/4 - 0s - loss: 0.7486 - val_loss: 0.6952
Epoch 10/1000
4/4 - 0s - loss: 0.7158 - val_loss: 0.6638
Epoch 11/1000
4/4 - 0s - loss: 0.6870 - val_loss: 0.6336
Epoch 12/1000
4/4 - 0s - loss: 0.6606 - val_loss: 0.6036
Epoch 13/1000
4/4 - 0s - loss: 0.6360 - val_loss: 0.5760
Epoch 14/1000
4/4 - 0s - loss: 0.6095 - val_loss: 0.5515
Epoch 15/1000
4/4 - 0s - loss: 0.5899 - val_loss: 0.5275
Epoch 16/1000
4/4 - 0s - loss: 0.5636 - val_loss: 0.5052
Epoch 17/1000
4/4 - 0s - loss: 0.5422 - val_loss: 0.4833
Epoch 18/1000
4/4 - 0s - loss: 0.5227 - 

In [25]:
from sklearn.metrics import accuracy_score

pred = model.predict(x_test)
print("pred :",pred)

predict_classes = np.argmax(pred,axis=1)
expected_classes = np.argmax(y_test,axis=1)
correct = accuracy_score(expected_classes,predict_classes)
print(f"Accuracy: {correct}")

pred : [[2.1349196e-03 8.9812571e-01 9.9739484e-02]
 [9.9714977e-01 2.8502322e-03 8.1919271e-10]
 [3.3267855e-07 5.0415215e-04 9.9949551e-01]
 [2.5299732e-03 8.9124262e-01 1.0622745e-01]
 [1.5885559e-03 9.5080304e-01 4.7608487e-02]
 [9.9567163e-01 4.3284437e-03 3.5155945e-09]
 [1.6114587e-02 9.8088968e-01 2.9956996e-03]
 [3.9404503e-04 2.7994221e-01 7.1966374e-01]
 [1.4744342e-03 4.9224898e-01 5.0627667e-01]
 [5.6844219e-03 9.8766464e-01 6.6509331e-03]
 [5.8788061e-04 3.6858854e-01 6.3082361e-01]
 [9.9403507e-01 5.9649297e-03 1.4435452e-08]
 [9.9858558e-01 1.4144462e-03 3.7722711e-10]
 [9.9356139e-01 6.4385533e-03 1.3363632e-08]
 [9.9743217e-01 2.5678657e-03 1.5091175e-09]
 [1.9646627e-03 9.5616299e-01 4.1872378e-02]
 [5.4013776e-06 3.9330292e-03 9.9606150e-01]
 [4.8977928e-03 9.8160052e-01 1.3501604e-02]
 [2.7047545e-03 8.3415580e-01 1.6313945e-01]
 [7.1307827e-06 4.2373985e-03 9.9575555e-01]
 [9.8929673e-01 1.0703308e-02 4.0565215e-08]
 [7.5579551e-04 3.4576711e-01 6.5347707e-01]
 [9

In [26]:
# Measure RMSE error.  RMSE is common for regression.
pred = model.predict(x_test)
score = np.sqrt(metrics.mean_squared_error(pred,y_test))
print(f"Final score (RMSE): {score}")

Final score (RMSE): 0.11318712681531906
