In [2]:
!pip install numpy
import numpy as np

     |████████████████████████████████| 14.5 MB 4.0 MB/s eta 0:00:01    |▋                               | 286 kB 4.0 MB/s eta 0:00:04


In [3]:
a = np.arange(9).reshape((3, 3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
c = (a > 1) & (a < 7)
c

array([[False, False,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [8]:
a[c]

array([2, 3, 4, 5, 6])

In [13]:
np.where((a > 1) & (a < 5))

(array([0, 1, 1]), array([2, 0, 1]))

In [12]:
(np.where((a > 2) & (a < 6) | (a == 7), -1, 100))

array([[100, 100, 100],
       [ -1,  -1,  -1],
       [100,  -1, 100]])

In [16]:
for x in zip(*(np.where((a > 1) & (a < 5)))):
    print(x)

(0, 2)
(1, 0)
(1, 1)


In [17]:
list(zip(*(np.where((a > 1) & (a < 5)))))

[(0, 2), (1, 0), (1, 1)]