In [1]:
# -- encoder : decoder anomaly detection : https://stackoverflow.com/questions/52437708/prepare-decoder-of-a-sequence-to-sequence-network-in-pytorch

In [ ]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array


### Return sequence false -->  lstm(4) just last state (batch_size,hidden)

In [6]:
# define model
inputs1 = Input(shape=(3, 3))
lstm1 = LSTM(4)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)
# define input data
data = array([[0.1,0.2,0.99], [0.2,0.5,0.1], [0.3,0.9,0.65]]).reshape((1,3,3))
# make and show prediction
print(model.predict(data))

[[-0.13260265  0.27385584 -0.24074206  0.2737454 ]]


### Return sequence true -->  lstm(4) just last state (batch_size,seq_len,hidden)

In [8]:
inputs1 = Input(shape=(3, 3))
lstm1 = LSTM(4, return_sequences=True)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)
# define input data
data = array([[0.1,0.2,0.99], [0.2,0.5,0.1], [0.3,0.9,0.65]]).reshape((1,3,3))
# make and show prediction
print(model.predict(data))

[[[ 0.0141136   0.06267215  0.05431435 -0.13560493]
  [-0.02658494 -0.01102044  0.04490502 -0.04736639]
  [-0.06545106 -0.07161186  0.06655654 -0.02885797]]]


#### Return state

#### Return state = true, 
#### out = (batch_size, hidden)
#### hidden = (batch_size,hidden) -- out same
#### cell = (batch_size,hidden)

In [10]:
inputs1 = Input(shape=(3, 3))
lstm1 = LSTM(4, return_state=True)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)
# define input data
data = array([[0.1,0.2,0.99], [0.2,0.5,0.1], [0.3,0.9,0.65]]).reshape((1,3,3))
# make and show prediction
out, hidden, cell = (model.predict(data))

print("out : ",out)
print("hidden : ",hidden)
print("cell : ",cell)

out :  [[ 0.15033197 -0.06739371 -0.03980701 -0.27022973]]
hidden :  [[ 0.15033197 -0.06739371 -0.03980701 -0.27022973]]
cell :  [[ 0.25727272 -0.12203526 -0.09423355 -0.5904674 ]]


#### Return state = true, 
#### out = (batch_size, seq, hidden)
#### hidden = (batch_size,hidden) -- out[-1] same
#### cell = (batch_size,hidden)

In [11]:
inputs1 = Input(shape=(3, 3))
lstm1 = LSTM(4, return_state=True, return_sequences=True)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)
# define input data
data = array([[0.1,0.2,0.99], [0.2,0.5,0.1], [0.3,0.9,0.65]]).reshape((1,3,3))
# make and show prediction
out, hidden, cell = (model.predict(data))

print("out : ",out)
print("hidden : ",hidden)
print("cell : ",cell)

out :  [[[-0.09043669  0.15893129 -0.00874605  0.09069443]
  [-0.11746418  0.13571349 -0.01326715  0.03862947]
  [-0.15278938  0.2230941  -0.01352364  0.04636482]]]
hidden :  [[-0.15278938  0.2230941  -0.01352364  0.04636482]]
cell :  [[-0.38634565  0.44384152 -0.03899081  0.11062123]]
