In [3]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM, Bidirectional
from numpy import array


### Return sequence false -->  lstm(4) just last state (batch_size,hidden)

In [ ]:
# define model
inputs1 = Input(shape=(3, 3))
lstm1 = LSTM(4)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)
# define input data
data = array([[0.1,0.2,0.99], [0.2,0.5,0.1], [0.3,0.9,0.65]]).reshape((1,3,3))
# make and show prediction
print(model.predict(data))

[[-0.13260265  0.27385584 -0.24074206  0.2737454 ]]


### Return sequence true -->  lstm(4) just last state (batch_size,seq_len,hidden)

In [ ]:
inputs1 = Input(shape=(3, 3))
lstm1 = LSTM(4, return_sequences=True)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)
# define input data
data = array([[0.1,0.2,0.99], [0.2,0.5,0.1], [0.3,0.9,0.65]]).reshape((1,3,3))
# make and show prediction
print(model.predict(data))

[[[ 0.0141136   0.06267215  0.05431435 -0.13560493]
  [-0.02658494 -0.01102044  0.04490502 -0.04736639]
  [-0.06545106 -0.07161186  0.06655654 -0.02885797]]]


#### Return state

#### Return state = true, 
#### out = (batch_size, hidden)
#### hidden = (batch_size,hidden) -- out same
#### cell = (batch_size,hidden)

In [ ]:
inputs1 = Input(shape=(3, 3))
lstm1 = LSTM(4, return_state=True)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)
# define input data
data = array([[0.1,0.2,0.99], [0.2,0.5,0.1], [0.3,0.9,0.65]]).reshape((1,3,3))
# make and show prediction
out, hidden, cell = (model.predict(data))

print("out : ",out)
print("hidden : ",hidden)
print("cell : ",cell)

out :  [[ 0.15033197 -0.06739371 -0.03980701 -0.27022973]]
hidden :  [[ 0.15033197 -0.06739371 -0.03980701 -0.27022973]]
cell :  [[ 0.25727272 -0.12203526 -0.09423355 -0.5904674 ]]


#### Return state = true, 
#### out = (batch_size, seq, hidden)
#### hidden = (batch_size,hidden) -- out[-1] same
#### cell = (batch_size,hidden)

In [ ]:
inputs1 = Input(shape=(3, 3))
lstm1 = LSTM(4, return_state=True, return_sequences=True)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)
# define input data
data = array([[0.1,0.2,0.99], [0.2,0.5,0.1], [0.3,0.9,0.65]]).reshape((1,3,3))
# make and show prediction
out, hidden, cell = (model.predict(data))

print("out : ",out)
print("hidden : ",hidden)
print("cell : ",cell)

out :  [[[-0.09043669  0.15893129 -0.00874605  0.09069443]
  [-0.11746418  0.13571349 -0.01326715  0.03862947]
  [-0.15278938  0.2230941  -0.01352364  0.04636482]]]
hidden :  [[-0.15278938  0.2230941  -0.01352364  0.04636482]]
cell :  [[-0.38634565  0.44384152 -0.03899081  0.11062123]]


### Bidirectional LSTM

In [7]:
inputs1 = Input(shape=(3, 3))
lstm1 = Bidirectional(LSTM(4, return_state=True, return_sequences=True))(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)
# define input data
data = array([[0.1,0.2,0.99], [0.2,0.5,0.1], [0.3,0.9,0.65]]).reshape((1,3,3))
# make and show prediction
a = (model.predict(data))
"""
print("out : ",out)
print("hidden : ",hidden)
print("cell : ",cell)
"""
print("a[0]",a[0].shape)
a


a[0] (1, 3, 8)


[array([[[-0.05059863,  0.04636485,  0.05786786,  0.07078998,
           0.01716897,  0.23533122,  0.18849233, -0.0549852 ],
         [ 0.01286594,  0.08022677,  0.05811954, -0.00762515,
          -0.07412362,  0.16171779,  0.11127771,  0.03534358],
         [ 0.04418893,  0.13021913,  0.0708093 , -0.03784038,
          -0.02641132,  0.12697817,  0.10407488,  0.01650312]]],
       dtype=float32),
 array([[ 0.04418893,  0.13021913,  0.0708093 , -0.03784038]],
       dtype=float32),
 array([[ 0.11788242,  0.2906269 ,  0.18503165, -0.08274363]],
       dtype=float32),
 array([[ 0.01716897,  0.23533122,  0.18849233, -0.0549852 ]],
       dtype=float32),
 array([[ 0.04637791,  0.5268264 ,  0.49135128, -0.1387937 ]],
       dtype=float32)]